### ISSUE TITLE
no localFile field

### ISSUE THREAD

**Issue by jpalmieri** [oorestisime/gatsby-source-dropbox#2] opened 2019-01-11 05:21 UTC
> The plugin makes use of the create remote node API of gatsby to locally download all the files in order to use them with other transformer plugins such as gatsby-transformer-sharp for images or gatsby-transformer-remark for markdown files.

I'd like to use transformer plugins like sharp for my images, but I'm not seeing the `localFile` field on DropboxNodes in GraphiQL. Am I missing something?

**Comment by oorestisime** [comment] 2019-01-11 06:41
Hm, its been some time i don't use this plugin but it did present localFiles. 
I seem to recall though i didn't explicitly test with images only with markdown files.

I hope to have some time to check this out in the following days

**Comment by jpalmieri** [comment] 2019-01-13 02:36
I had some time to look at this and it looks like `createRemoteFileNode` might be silently failing (or just not completing) because the url returned by `getTemporaryUrl` returns a stream (per Dropbox's API docs: https://dropbox.github.io/dropbox-sdk-js/Dropbox.html#filesGetTemporaryLink__anchor) and `createRemoteFileNode` doesn't know how to download it.

**Comment by jpalmieri** [comment] 2019-01-13 02:37
I'm not sure how to handle that issue, if that is the problem.

**Comment by jpalmieri** [comment] 2019-01-13 02:40
FYI I'm using this on a starter with gatsby v2.0.76

**Comment by oorestisime** [comment] 2019-01-13 08:17
Right so i PRed a fix for the failing silently part https://github.com/gatsbyjs/gatsby/pull/10980

I ll test what you describe today (the streaming issue) and get back to you

**Comment by oorestisime** [comment] 2019-01-13 08:31
So i gave this a quick test and launched the graphiql editor to test the localFile. I have gatsby 2.0.63 

```graphql
  allDropboxNode(limit: 1) {
    edges {
      node {
        id
        name
        localFile {
          childImageSharp {
            fluid(maxWidth: 500) {
              src
              srcSet
            }
          }
        }
      }
    }
  }
```

And i do get a result 

```graphql
{
  "data": {
    "allDropboxNode": {
      "edges": [
        {
          "node": {
            "id": "id:ERYriBGsegMAAAAAAAAWfA",
            "name": "test.png",
            "localFile": {
              "childImageSharp": {
                "fluid": {
                  "src": "/static/b0696d3d06e55e865234488c59f068ef/3f86a/7bc1c86b0ee45d0055e47e810c93be46.png",
                  "srcSet": "/static/b0696d3d06e55e865234488c59f068ef/5c800/7bc1c86b0ee45d0055e47e810c93be46.png 125w,\n/static/b0696d3d06e55e865234488c59f068ef/4c0da/7bc1c86b0ee45d0055e47e810c93be46.png 250w,\n/static/b0696d3d06e55e865234488c59f068ef/3f86a/7bc1c86b0ee45d0055e47e810c93be46.png 500w,\n/static/b0696d3d06e55e865234488c59f068ef/74631/7bc1c86b0ee45d0055e47e810c93be46.png 750w,\n/static/b0696d3d06e55e865234488c59f068ef/8bc39/7bc1c86b0ee45d0055e47e810c93be46.png 1000w,\n/static/b0696d3d06e55e865234488c59f068ef/13475/7bc1c86b0ee45d0055e47e810c93be46.png 1500w,\n/static/b0696d3d06e55e865234488c59f068ef/8e4bc/7bc1c86b0ee45d0055e47e810c93be46.png 4000w"
                }
              }
            }
          }
        }
      ]
    }
  }
}
```

So multiple things come to my mind: 

* Can you show some code so i can understand what is happening? 
* Is this happening only for images or have you tried testing with other files?
* which version of gatsby-source-filesystem do you use?

**Comment by oorestisime** [comment] 2019-01-13 08:45
OK i manage to reproduce this locally with the latest `gatsby-source-filesystem`

**Comment by oorestisime** [comment] 2019-01-13 09:20
So the issue here is that `2.0.12` introduced a regression because it tries to get the remote filename so that cache folder contains sensible names. OTOH dropbox creates urls and not filenames to get the content so the plugin thinks that the remote filename is something like:

`AADblPh0XxJ88ogCFwZf7AQ9BM42PNgL4LTkqa9-oV_C9L07BUvZ2Hzakt0yHGLFOhE-EzrIKCqsMhVNINf4zat2ri4NI9DmbNo275UdYHF9WBIDygLesHe7I_G7vQvytkuEn94OOgQpa9QygfUVP-cSk3coQVPAh2RnTyrp8-TQviuj-h423N6nk_amibdjrOeeRyvWuWZvIMBOh9MIcHe5bcsYIQiRlRYUWplYgD9iHkxY6oLBQEEdj4Ac3sTR7V1Rn0zDcKFA4l2ikGAZtdRxwxjzZrD3Abaajuupji9pmA`
which is more characters than the allowed on ext4 linux filesystems and it silently fails :/

I ll work on a fix for the remote-filesystem API but in the meantime the only solution for now is to block the version to `2.0.11`

Sorry for the hassle

**Comment by lablancas** [comment] 2019-01-20 16:07
I am attempting to fix this problem in #3 . I'm still having an issue with the code. Check out the PR if you think you might be able to help me out.

The solution does use a deprecated method from the Dropbox API so this would just be a temporary solution for people who want to use this plugin.

**Comment by lablancas** [comment] 2019-01-20 16:12
actually, I'll probably convert PR #3 to a transformer plugin so that people can use the plugin as a temporary fix without changing this plugins code.

**Comment by oorestisime** [comment] 2019-01-20 22:34
well the issue is already fixed in a PR in gatsby. i am waiting that to get merged and release the new version. on current master there's already the work prepared for the change in gatsby-source-filesystem. it shouldn't be long. i am hoping for a release this week.

**Closed** 2019-01-23 18:36 UTC
Labels: bug

**Comment by oorestisime** [comment] 2019-01-23 21:13
I ve just released a new version with the new version of gatsby-source-filesystem. thanks to both of you for your input!
